apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: helloworld
    service: world
    version: green
    shard: green
  name: world-green
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      application: helloworld
      service: world
      version: green
      shard: green
  template:
    metadata:
      labels:
        application: helloworld
        service: world
        version: green
        shard: green
      annotations:
        autoscaling.knative.dev/minScale: "1" 
    spec:
      containers:
      - name: world
        image: public.ecr.aws/z4m0n1r4/world
        imagePullPolicy: Always
        env:
        - name: SHARD
          value: "green"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://wavefront-proxy.supreme-doodle.svc.cluster.local:4317"
        ports:
        - containerPort: 5002
          name: application
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: supreme-doodle
spec: 
  selector:
    application: helloworld
    service: world  
  type: ClusterIP
  ports:
    - appProtocol: http
      port: 5002
  # - name: http
    # protocol: TCP
    # port: 5002

