apiVersion: newrelic.com/v1beta1
kind: Instrumentation
metadata:
  name: newrelic-instrumentation-python
  namespace: newrelic
spec:
  agent:
    language: python
    image: newrelic/newrelic-python-init:latest
    env:
      - name: NEW_RELIC_APP_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['app.kubernetes.io/name']
  podLabelSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: "In"
        values: ["frontend", "hello", "world"]
  namespaceLabelSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["supreme-doodle"]
