apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: world
    app.kubernetes.io/instance: world-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
  name: world
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: world
      app.kubernetes.io/instance: world-xyzz
      app.kubernetes.io/version: "0.9.1"
      app.kubernetes.io/component: service
      app.kubernetes.io/part-of: helloworld
      app.kubernetes.io/managed-by: kubectl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: world
        app.kubernetes.io/instance: world-xyzz
        app.kubernetes.io/version: "0.9.1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: helloworld
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
      - name: world
        image: ghcr.io/scrogatl/doodle-world:latest
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 5002
          name: application
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: supreme-doodle
  labels:
    app.kubernetes.io/name: world
    app.kubernetes.io/instance: world-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
spec: 
  selector:
    app.kubernetes.io/name: world
    app.kubernetes.io/instance: world-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
  type: ClusterIP
  ports:
  - name: http
    # protocol: TCP
    appProtocol: http
    port: 5002