apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hello
    app.kubernetes.io/instance: hello-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
  name: hello
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
      app.kubernetes.io/instance: hello-xyzz
      app.kubernetes.io/version: "0.9.1"
      app.kubernetes.io/component: service
      app.kubernetes.io/part-of: helloworld
      app.kubernetes.io/managed-by: kubectl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
        app.kubernetes.io/instance: hello-xyzz
        app.kubernetes.io/version: "0.9.1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: helloworld
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
      - name: hello
        # image: public.ecr.aws/z4m0n1r4/hello
        image: ghcr.io/scrogatl/doodle-hello:latest
        imagePullPolicy: Always
        env:
        - name: SHARD
          value: "blue"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: NEW_RELIC_LICENSE_KEY
          value:  "$NEW_RELIC_LICENSE_KEY"
        - name: DOODLE-VERSION
          value: "V0.99.4"
        - name: ERROR_THRESH
          value: "1"
        - name: WEATHER_HOST
          value: "weather"
        - name: WEATHER_THRESH
          value: "50"
        ports:
        - containerPort: 5001
          name: application
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: supreme-doodle
  labels:
    app.kubernetes.io/name: hello
    app.kubernetes.io/instance: hello-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
spec: 
  selector:
    app.kubernetes.io/name: hello
    app.kubernetes.io/instance: hello-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
  type: ClusterIP
  ports:
  - name: http
    # protocol: TCP
    appProtocol: http
    port: 5001