apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: helloworld
    service: loadgen-local
    shard: blue
    version: loadgen-blue
  name: loadgen-blue
  namespace: tko-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      application: helloworld
      service: loadgen-local
      shard: blue
  template:
    metadata:
      labels:
        application: helloworld
        service: loadgen-local
        shard: blue
    spec:
      containers:
      - name: loadgen
        image: public.ecr.aws/z4m0n1r4/sd-loadgen
        imagePullPolicy: Always
        env:
        - name: FRONTEND_HOST
          value: "frontend"
          # value: "frontend.demo.internal"
        - name: PYTHONUNBUFFERED
          value: "1"
