services:
  # world-ruby:
  #   build: ../../gitops-doodle-world-ruby/
  #   image: gitops-doodle-world-ruby
  #   container_name: world-ruby
  #   ports:
  #     - "5003:5003"
  #   command: ["bundle", "exec", "rackup", "--host", "0.0.0.0", "-p", "5003"]

  world:
    build: ../../gitops-doodle-world
    image: gitops-doodle-world
    container_name: world
    ports:
      - "5002:5002"
    command: ["flask", "run", "--host=0.0.0.0", "-p 5002"]

  hello:
    build: ../../gitops-doodle-hello
    image: gitops-doodle-hello
    container_name: hello
    ports:
      - "5001:5001"
    environment:
      - SHARD=docker-local
      - WEATHER_HOST=weather-java
      - ERROR_THRESH=5
      - WEATHER_THRESH=90
      - PYTHONUNBUFFERED=1
    command: ["flask", "run", "--host=0.0.0.0", "-p 5001"]

  frontend:
    build: ../../gitops-doodle-frontend
    image: gitops-doodle-frontend
    container_name: frontend
    environment:
      - HELLO_HOST=hello
      - HELLO_PORT=443
      - WORLD_HOST=world
      - WPORT=5002
      - WORLD_HOST_RUBY=world-ruby
      - WPORT_RUBY=5003
      - RUBY_WORLD=1
      - PYTHONUNBUFFERED=1
    command: ["flask", "run", "--host=0.0.0.0", "-p 5000"]

  weather:
    build: ../../gitops-doodle-weather
    image: gitops-doodle-weather
    container_name: weather
    environment:
      - SHARD=docker-local
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}

  weather-java:
    build: ../../gitops-doodle-weather-java
    image: gitops-doodle-weather-java
    container_name: weather-java
    ports:
      - "5100:5100"
    environment:
      - SHARD=docker-local
      - SERVER_PORT=5100

  loadgen:
    build: ../../gitops-doodle-loadgen
    environment:
      - F_HOST=frontend
      - WORLD_HOST=world
      - SLEEP_TIME=800
      - PYTHONUNBUFFERED=1
      - SHARD=docker-local
