apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: supreme-doodle
spec: 
  selector:
    application: helloworld
    service: frontend  
  type: ClusterIP
  ports:
  - name: http
    # protocol: TCP
    appProtocol: http
    port: 5000
