name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
   branches: [ "main" ]

jobs:
  build-push-frontend:
    runs-on: ubuntu-latest
    steps:
      
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
    
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: scrogatl
          password: ${{secrets.GITHUB_TOKEN}}      

      - name: Build
        run: |
          docker build . --tag ghcr.io/scrogatl/doodle-frontend:latest 
          docker push ghcr.io/scrogatl/doodle-frontend:latest
