apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: helloworld
    service: customer-endpoint
    shard: blue
    version: customer-endpoint
  name: customer-endpoint
  namespace: tko-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      application: helloworld
      service: customer-endpoint
      shard: blue
  template:
    metadata:
      labels:
        application: helloworld
        service: customer-endpoint
        shard: blue
    spec:
      containers:
      - name: loadgen
        image: public.ecr.aws/z4m0n1r4/sd-loadgen
        imagePullPolicy: Always
        env:
        - name: FRONTEND_HOST
          value: "frontend"
          # value: "frontend.demo.internal"
        - name: SLEEP_TIME
          value: "1000"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: ENVRIONMENT
          value: "east"
      

