apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: supreme-doodle
spec: 
  selector:
    application: helloworld
    service: hello
  type: ClusterIP
  ports:
  - name: http
    # protocol: TCP
    appProtocol: http
    port: 5001