apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: helloworld
    service: world
    version: blue
    shard: blue
  name: world-blue
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      application: helloworld
      service: world
      version: blue
      shard: blue
  template:
    metadata:
      labels:
        application: helloworld
        service: world
        version: blue
        shard: blue
    spec:
      containers:
      - name: world
        image: public.ecr.aws/z4m0n1r4/world
        imagePullPolicy: Always
        env:
        - name: SHARD
          value: "blue"
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 5002
          name: application
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: supreme-doodle
spec: 
  selector:
    application: helloworld
    service: world  
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 5002

