name: Build and push Weather container
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
   branches: [ "main" ]

jobs:
  build-push-weather:
    runs-on: ubuntu-latest
    steps:
      
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
    
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          # username: ${{github.actor}}
          username: scrogatl
          password: ${{secrets.GITHUB_TOKEN}}      

      - name: 'Build'
        run: |
          docker build . --tag ghcr.io/scrogatl/doodle-weather:latest 
          docker push ghcr.io/scrogatl/doodle-weather:latest
