version: '2'

services:
  world-ruby:
    image: gitops-doodle-world-ruby
    container_name: world-ruby
    environment: 
      - SHARD=blue

  world:
    image: gitops-doodle-world
    container_name: world
    environment: 
      - SHARD=blue
      - PYTHONUNBUFFERED=1

  hello:
    image: gitops-doodle-hello
    container_name: hello
    environment: 
      - SHARD=blue
      - PYTHONUNBUFFERED=1

  frontend:
    image: gitops-doodle-frontend
    container_name: frontend
    environment: 
      - HELLO_HOST=hello
      - WORLD_HOST=world
      - WORLD_HOST_RUBY=world-ruby
      - WPORT_RUBY=5003
      - SHARD=blue
      - PYTHONUNBUFFERED=1

  loadgen:
    image: gitops-doodle-loadgen
    container_name: loadgen
    environment: 
      - FRONTEND_HOST=frontend
      - WORLD_HOST=world
      - SLEEP_TIME=1000
      - PYTHONUNBUFFERED=1
