apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: doodle-weather-java
    application: helloworld
    service: doodle-weather-java
    version: blue
    shard: blue
  name: doodle-weather-java
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: doodle-weather-java
      application: helloworld
      service: doodle-weather-java
      version: blue
      shard: blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doodle-weather-java
        application: helloworld
        service: doodle-weather-java
        version: blue
        shard: blue
    spec:
      containers:
      - name: doodle-weather-java
        image: ghcr.io/scrogatl/doodle-weather-java:main
        imagePullPolicy: Always
        env:
        - name: SHARD
          value: "blue"
        - name: PYTHONUNBUFFERED
          value: "1"
        #- name: NEW_RELIC_LICENSE_KEY
        #  value:  "{{ .Values.nr_key }}"
        - name: OTEL_SERVICE_NAME
          value: "weather-service" 
        ports:
        - containerPort: 5100
          name: application
          protocol: TCP
