apiVersion: v1
kind: Service
metadata:
  name: doodle-hello
  namespace: supreme-doodle
  labels:
    app.kubernetes.io/name: doodle-hello
    app.kubernetes.io/instance: hello-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
spec: 
  selector:
    app.kubernetes.io/name: doodle-hello
    app.kubernetes.io/instance: hello-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
  type: ClusterIP
  ports:
  - name: http
    # protocol: TCP
    appProtocol: http
    port: 5001
