apiVersion: v1
kind: Service
metadata:
  name: doodle-weather
  namespace: supreme-doodle
spec: 
  selector:
    application: helloworld
    service: doodle-weather
  type: ClusterIP
  ports:
  - name: http
    # protocol: TCP
    appProtocol: http
    port: 5100
