apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
    service: world
    shard: green
  name: world-green
  namespace: observability-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      service: world
      shard: green
  template:
    metadata:
      labels:
        app: helloworld
        service: world
        shard: green
    spec:
      containers:
      - name: world
        image: public.ecr.aws/z4m0n1r4/world
        imagePullPolicy: Always
        env:
        - name: SHARD
          value: "green"
        - name: PYTHONUNBUFFERED
          value: "1"
        #command:
        #- "java"
        #- "-jar"
        #- "/shopping.jar"
        #- "server"
        #- "/conf/shopping-app.yaml"
        ports:
        - containerPort: 5002
          name: application
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: observability-demo
spec: 
  selector:
    app: helloworld
    service: world  
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 5002

